# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Test Library

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_app:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: install playwright
        run: npm init playwright@latest
      - name: Run the project
        run: npm run start &
      - name: Run server
        run: npm run server &
      - name: Run tests
        run: npm run test &
